### ISSUE TITLE
Multiple ideas

### ISSUE THREAD

**Issue by bradyakent** [BradyFromDiscord/CCPL#23]
Once these each have their own fleshed out issue ticket, close this issue.
- [x] Storage API - warehouse storage system (players or turtles should be able to access this)
- [x] Supply API - take supplies from warehouses, bring them to individual projects. Projects should be able to request supplies.
- [x] Mining API - automated mining that can detect veins of ore underground. Maybe figure out a way to find out what ores are available (i.e. if there are ores added by mods, watch for them too)

**Comment by BradyFromDiscord** [comment]
#24 Storage API

**Comment by bradyakent** [comment]
Each API has now been expanded into their own issues.
